import type { SkillNodeDef } from '../types/skillTree';

export const SKILL_TREE: SkillNodeDef[] = [
  // ── ANALYSIS BRANCH ──
  {
    key: 'basic_charts',
    name: 'Basic Charts',
    description: 'Unlock PnL curve chart',
    branch: 'analysis',
    tier: 1,
    icon: 'ChartLine',
    requiredLevel: 2,
    prerequisiteKeys: [],
    feature: 'pnl_curve_chart',
  },
  {
    key: 'pair_breakdown',
    name: 'Pair Breakdown',
    description: 'Win rate breakdown by trading pair',
    branch: 'analysis',
    tier: 2,
    icon: 'PieChart',
    requiredLevel: 5,
    prerequisiteKeys: ['basic_charts'],
    feature: 'pair_analytics',
  },
  {
    key: 'advanced_metrics',
    name: 'Advanced Metrics',
    description: 'Sharpe ratio, Sortino, and expectancy',
    branch: 'analysis',
    tier: 3,
    icon: 'Calculator',
    requiredLevel: 9,
    requiredHexaStat: { axis: 'profitability', minScore: 40 },
    prerequisiteKeys: ['pair_breakdown'],
    feature: 'advanced_stats',
  },
  {
    key: 'correlation_matrix',
    name: 'Correlation Matrix',
    description: 'Emotion × PnL heatmap',
    branch: 'analysis',
    tier: 4,
    icon: 'Grid3x3',
    requiredLevel: 14,
    requiredHexaStat: { axis: 'consistency', minScore: 50 },
    prerequisiteKeys: ['advanced_metrics'],
    feature: 'correlation_view',
  },

  // ── RISK BRANCH ──
  {
    key: 'drawdown_tracker',
    name: 'Drawdown Tracker',
    description: 'Drawdown chart + alerts',
    branch: 'risk',
    tier: 1,
    icon: 'TrendingDown',
    requiredLevel: 3,
    prerequisiteKeys: [],
    feature: 'drawdown_chart',
  },
  {
    key: 'position_sizer',
    name: 'Position Sizer',
    description: 'Position size calculator based on risk %',
    branch: 'risk',
    tier: 2,
    icon: 'SlidersHorizontal',
    requiredLevel: 6,
    prerequisiteKeys: ['drawdown_tracker'],
    feature: 'position_calculator',
  },
  {
    key: 'risk_heatmap',
    name: 'Risk Heatmap',
    description: 'Exposure by pair and timeframe',
    branch: 'risk',
    tier: 3,
    icon: 'Flame',
    requiredLevel: 10,
    requiredHexaStat: { axis: 'risk_management', minScore: 45 },
    prerequisiteKeys: ['position_sizer'],
    feature: 'risk_heatmap',
  },

  // ── PSYCHOLOGY BRANCH ──
  {
    key: 'emotion_log',
    name: 'Emotion Log',
    description: 'Tag emotional state per trade',
    branch: 'psychology',
    tier: 1,
    icon: 'Smile',
    requiredLevel: 2,
    prerequisiteKeys: [],
    feature: 'emotion_tagging',
  },
  {
    key: 'tilt_detector',
    name: 'Tilt Detector',
    description: 'Warning shown after 2+ consecutive negative tags',
    branch: 'psychology',
    tier: 2,
    icon: 'AlertTriangle',
    requiredLevel: 7,
    prerequisiteKeys: ['emotion_log'],
    feature: 'tilt_warning',
  },
  {
    key: 'mood_analytics',
    name: 'Mood Analytics',
    description: 'PnL breakdown by emotional state',
    branch: 'psychology',
    tier: 3,
    icon: 'Brain',
    requiredLevel: 11,
    requiredHexaStat: { axis: 'emotional_ctrl', minScore: 40 },
    prerequisiteKeys: ['tilt_detector'],
    feature: 'mood_charts',
  },

  // ── EXECUTION BRANCH ──
  {
    key: 'trade_timer',
    name: 'Trade Timer',
    description: 'Track trade hold duration automatically',
    branch: 'execution',
    tier: 1,
    icon: 'Clock',
    requiredLevel: 3,
    prerequisiteKeys: [],
    feature: 'duration_tracking',
  },
  {
    key: 'setup_library',
    name: 'Setup Library',
    description: 'Save and categorize trade setups',
    branch: 'execution',
    tier: 2,
    icon: 'Bookmark',
    requiredLevel: 8,
    prerequisiteKeys: ['trade_timer'],
    feature: 'setup_templates',
  },
  {
    key: 'execution_score',
    name: 'Execution Score',
    description: 'Grade entry and exit quality per trade',
    branch: 'execution',
    tier: 3,
    icon: 'Target',
    requiredLevel: 12,
    requiredHexaStat: { axis: 'execution', minScore: 45 },
    prerequisiteKeys: ['setup_library'],
    feature: 'execution_grading',
  },
];
